[project]
name = "inspect-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.74.0",
    "inspect-ai",
    "langchain>=1.2.17",
    "langgraph>=1.1.10",
    "mcp>=1.27.0",
    "openai>=2.33.0",
    "pydantic>=2.13.3",
]

[tool.uv.sources]
inspect-ai = { path = "../inspect_ai", editable = true }
